CREATE TABLE stores(
                       store_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       store_name VARCHAR(150) NOT NULL,
                       address_line_1 VARCHAR(255) NOT NULL,
                       address_line_2 VARCHAR(100),
                       city_id INT NOT NULL,
                       state_id INT NOT NULL,
                       zip_code VARCHAR(6),
                       PRIMARY KEY (store_id)
);


CREATE TABLE accounts (
                          user_id serial PRIMARY KEY,
                          username VARCHAR ( 50 ) UNIQUE NOT NULL,
                          password VARCHAR ( 50 ) NOT NULL,
                          email VARCHAR ( 255 ) UNIQUE NOT NULL,
                          created_on TIMESTAMP NOT NULL,
                          last_login TIMESTAMP
);


SELECT *
FROM stores;

