-- list the names of each birthing center/community clinic as well as the number of pregnancies
-- that are due for the month of July this year (2022).
-- For this purpose you will count a pregnancy towards a facility
-- if the primary midwife is from that facility (and not based on the final birthing location).
-- You should also use the “final agreed up on” due date if that is present,
-- in order to figure out if the pregnancy will fall into a specific month.
-- Otherwise (if that information is not yet available), use the expected time frame for birth (year-month) that was provided initially.