-- list the health care card, name of mothers
-- who have had more than one baby in a single pregnancy.
-- List them only once even if they had multiple pregnancies where they had more than one baby.
-- Count the babies whether they are born or not (yet).