-- List the title and release date of all the movies
-- that were released in both (and not just either) English and French and
-- also had 5 or more reviews. Order the output by release date and then by title.
-- Whether the movies had been released in other languages are irrelevant.