-- Find the movies that fell out of popularity.
-- List the title and release date of all the movies that had an average rating of 7 or above before 2019
-- but has an average rating of 5 or lower starting 2019
-- (be careful to take into account movies with no reviews in the later period as 0 rating).
-- Order the output by their release date and then by title.
