-- List all the languages in the database and the genre
-- that has most movies for that language.
-- If two genres are equally the most popular for the language, produce two rows in the output (and so forth).
-- Order the output by languages and then by genre.

-- A sample format is given below:
-- language | genre
-- ----------+-----------
-- French | Drama
-- French | Sci-Fi
-- German | Drama
-- Greek | Action
-- Greek | Adventure
